apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::373927941650:role/eksctl-sudha-nodegroup-spot-NodeInstanceRole-8IxignTFMIb2
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::373927941650:user/ramesh
      username: ramesh
    
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 9fc35a67-d125-49bf-9393-4afe5cce04e6