apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: 373927941650:role/eksctl-sudha-nodegroup-spot-NodeInstanceRole-iXEM2cgV5CwI
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::373927941650:user/ramesh
      username: ramesh
    
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 974b5f3f-c267-4a29-80f2-e38d2d561546